### ISSUE TITLE
Issue compilation on Ubuntu 22.04

### ISSUE THREAD

**Issue by cgadal** [msolids/musen#27]
Hello,

I just discovered MUSEN and I wanted to try it. I first tried the compilation on my laptop before going on the cluster, and everything went fine up to `cmake --build . --parallel $(nproc)` (full log below). This is unfortunately beyond what I can fix by myself; would you have time to help?

OS: Ubuntu 20.4

#### output of: `cmake-DCMAKE_INSTALL_PREFIX=../install`

```
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 11.5.119
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found CUDAToolkit: /usr/include (found version "11.5.119") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.a (found version "3.12.4") 
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindOpenGL.cmake:315 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  MusenGUI/CMakeLists.txt:31 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Configuring done
-- Generating done
-- Build files have been written to: /home/s88422cg/Documents/Work/Research/Codes/musen/build

```

#### output of  `cmake --build . --parallel $(nproc)`:

```
[  1%] Building CXX object CMakeFiles/libmusen_static.dir/Databases/MaterialsDatabase/BaseProperty.cpp.o
[  1%] Building CXX object CMakeFiles/libmusen_static.dir/Databases/MaterialsDatabase/ConstProperty.cpp.o
[  1%] Building CXX object CMakeFiles/libmusen_static.dir/Databases/GeometriesDatabase/GeometriesDatabase.cpp.o
[  1%] Building CXX object CMakeFiles/libmusen_static.dir/Databases/MaterialsDatabase/Mixture.cpp.o
[  2%] Building CXX object CMakeFiles/libmusen_static.dir/Databases/MaterialsDatabase/Interaction.cpp.o
[  2%] Building CXX object CMakeFiles/libmusen_static.dir/CMusen/CMusen.cpp.o
[  3%] Building CXX object CMakeFiles/libmusen_static.dir/Databases/MaterialsDatabase/MaterialsDatabase.cpp.o
[  3%] Building CXX object CMakeFiles/libmusen_static.dir/Databases/AgglomerateDatabase/AgglomeratesDatabase.cpp.o
[  4%] Building CXX object CMakeFiles/libmusen_static.dir/Databases/MaterialsDatabase/TPProperty.cpp.o
[  4%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ExternalForce/CentrifugalCasting/ModelEFCentrifugalCasting.cpp.o
[  5%] Building CXX object CMakeFiles/libmusen_static.dir/Databases/MaterialsDatabase/Compound.cpp.o
[  6%] Building CXX object CMakeFiles/libmusen_static.dir/Databases/MaterialsDatabase/Correlation.cpp.o
[  6%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ExternalForce/HeatTransfer/ModelEFHeatTransfer.cu.o
[  7%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ExternalForce/ViscousField/ModelEFViscousField.cu.o
[  7%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ExternalForce/ViscousField/ModelEFViscousField.cpp.o
[  8%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ExternalForce/HeatTransfer/ModelEFHeatTransfer.cpp.o
[  7%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ExternalForce/LiquidDiffusion/ModelEFLiquidDiffusion.cu.o
[  9%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ExternalForce/LiquidDiffusion/ModelEFLiquidDiffusion.cpp.o
[  9%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ExternalForce/CentrifugalCasting/ModelEFCentrifugalCasting.cu.o
[ 10%] Building CXX object CMakeFiles/libmusen_static.dir/Models/LiquidBonds/CapilaryViscous/ModelLBCapilarViscous.cpp.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 10%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/ChealNess/ModelPPChealNess.cpp.o
[ 11%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/ChealNess/ModelPPChealNess.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 11%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/HeatConduction/ModelPPHeatConduction.cpp.o
[ 12%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/HeatConduction/ModelPPHeatConduction.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 12%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/Hertz/ModelPPHertz.cpp.o
[ 13%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/HertzMindlin/ModelPPHertzMindlin.cpp.o
[ 13%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/HertzMindlin/ModelPPHertzMindlin.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 14%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/HertzMindlinLiquid/ModelPPHertzMindlinLiquid.cpp.o
[ 14%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/HertzMindlinVdW/ModelPPHertzMindlinVdW.cpp.o
[ 14%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/HertzMindlinVdW/ModelPPHertzMindlinVdW.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 15%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/JKR/ModelPPJKR.cpp.o
[ 15%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/JKR/ModelPPJKR.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 16%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/LinearElastic/ModelPPLinearElastic.cpp.o
[ 16%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/LinearElastic/ModelPPLinearElastic.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 17%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/PopovJKR/ModelPPPopovJKR.cpp.o
[ 17%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/SimpleViscoElastic/ModelPPSimpleViscoElastic.cpp.o
[ 18%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/SimpleViscoElastic/ModelPPSimpleViscoElastic.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 18%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/SinteringTemperature/ModelPPSinteringTemperature.cpp.o
[ 19%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/SinteringTemperature/ModelPPSinteringTemperature.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 19%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/TestSinteringModel/ModelPPSintering.cpp.o
[ 20%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleParticle/TestSinteringModel/ModelPPSintering.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 20%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWHeatTransfer/ModelPWHeatTransfer.cpp.o
[ 21%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWHeatTransfer/ModelPWHeatTransfer.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 21%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWHertzMindlin/ModelPWHertzMindlin.cpp.o
[ 21%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWHertzMindlin/ModelPWHertzMindlin.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 22%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWHertzMindlinLiquid/ModelPWHertzMindlinLiquid.cpp.o
[ 22%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWHertzMindlinLiquid/ModelPWHertzMindlinLiquid.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 23%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWJKR/ModelPWJKR.cpp.o
[ 23%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWJKR/ModelPWJKR.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 24%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWPopovJKR/ModelPWPopovJKR.cpp.o
[ 24%] Building CXX object CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWSimpleViscoElastic/ModelPWSimpleViscoElastic.cpp.o
[ 25%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWSimpleViscoElastic/ModelPWSimpleViscoElastic.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 25%] Building CXX object CMakeFiles/libmusen_static.dir/Models/SolidBonds/BondModelAerogel/ModelSBAerogel.cpp.o
[ 26%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/SolidBonds/BondModelAerogel/ModelSBAerogel.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 26%] Building CXX object CMakeFiles/libmusen_static.dir/Models/SolidBonds/BondModelCreep/ModelSBCreep.cpp.o
[ 27%] Building CUDA object CMakeFiles/libmusen_static.dir/Models/SolidBonds/BondModelCreep/ModelSBCreep.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:328: CMakeFiles/libmusen_static.dir/Models/ExternalForce/ViscousField/ModelEFViscousField.cu.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:272: CMakeFiles/libmusen_static.dir/Models/ExternalForce/HeatTransfer/ModelEFHeatTransfer.cu.o] Error 1
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:244: CMakeFiles/libmusen_static.dir/Models/ExternalForce/CentrifugalCasting/ModelEFCentrifugalCasting.cu.o] Error 1
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:398: CMakeFiles/libmusen_static.dir/Models/ParticleParticle/HeatConduction/ModelPPHeatConduction.cu.o] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:440: CMakeFiles/libmusen_static.dir/Models/ParticleParticle/HertzMindlin/ModelPPHertzMindlin.cu.o] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:482: CMakeFiles/libmusen_static.dir/Models/ParticleParticle/HertzMindlinVdW/ModelPPHertzMindlinVdW.cu.o] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:538: CMakeFiles/libmusen_static.dir/Models/ParticleParticle/LinearElastic/ModelPPLinearElastic.cu.o] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:664: CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWHeatTransfer/ModelPWHeatTransfer.cu.o] Error 1
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:370: CMakeFiles/libmusen_static.dir/Models/ParticleParticle/ChealNess/ModelPPChealNess.cu.o] Error 1
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:510: CMakeFiles/libmusen_static.dir/Models/ParticleParticle/JKR/ModelPPJKR.cu.o] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:636: CMakeFiles/libmusen_static.dir/Models/ParticleParticle/TestSinteringModel/ModelPPSintering.cu.o] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:692: CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWHertzMindlin/ModelPWHertzMindlin.cu.o] Error 1
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:608: CMakeFiles/libmusen_static.dir/Models/ParticleParticle/SinteringTemperature/ModelPPSinteringTemperature.cu.o] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:790: CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWSimpleViscoElastic/ModelPWSimpleViscoElastic.cu.o] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:748: CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWJKR/ModelPWJKR.cu.o] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:720: CMakeFiles/libmusen_static.dir/Models/ParticleWall/PWHertzMindlinLiquid/ModelPWHertzMindlinLiquid.cu.o] Error 1
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:818: CMakeFiles/libmusen_static.dir/Models/SolidBonds/BondModelAerogel/ModelSBAerogel.cu.o] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:580: CMakeFiles/libmusen_static.dir/Models/ParticleParticle/SimpleViscoElastic/ModelPPSimpleViscoElastic.cu.o] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:846: CMakeFiles/libmusen_static.dir/Models/SolidBonds/BondModelCreep/ModelSBCreep.cu.o] Error 1
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/libmusen_static.dir/build.make:300: CMakeFiles/libmusen_static.dir/Models/ExternalForce/LiquidDiffusion/ModelEFLiquidDiffusion.cu.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:103: CMakeFiles/libmusen_static.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by vasylskorych** [comment]
Hello, 

at first glance, the problem is in the incompatibility of gcc and cuda versions. Try to update your cuda toolkit - in my Ubuntu 22.04 I could successfully compile with gcc 11.4 and cuda 11.7

**Comment by vasylskorych** [comment]
Partially fixed in #47. Also, see CUDA-GCC compatibilty, e.g. here: [https://gist.github.com/ax3l/9489132](https://gist.github.com/ax3l/9489132)
