### ISSUE TITLE
MUSEN compilation errors out with GCC 8 + CUDA 11 and also with GCC 12 + CUDA 12 on Linux (compiles fine with GCC 11 + CUDA 11)

### ISSUE THREAD

**Issue by secondspass** [msolids/musen#34]
Hello,

I figured I'd open this issue so that you are aware (and if someone else runs into the same issue that I do, they'll see this when they google it). **Long story short, I needed to use gcc/11.5.0 + cuda/11.7.1 to properly compile MUSEN without error**. Following are the details of the issues I ran into when trying other combinations.

## Building with GCC 8.5.0 + CUDA 11.7.1 

I was trying to build MUSEN on an HPC cluster with the gcc/8.5.0 and cuda/11.7.1

I build Protobuf first like so (libz is already installed on the cluster as an RPM, so need for me to build that separately):

```
wget https://github.com/protocolbuffers/protobuf/releases/download/v21.0/protobuf-cpp-3.21.0.tar.gz
tar xzf protobuf-cpp-3.21.0.tar.gz
cd protobuf-3.21.0
CC=gcc CXX=g++ ./configure --prefix=$PWD/install --enable-shared
make clean
make -j16
make install
export PROTOBUF_DIR=$PWD/install
```

Then try to build MUSEN like so
```
git clone https://github.com/msolids/musen.git
cd musen
bash Version/generate_build_version.sh
mkdir build install
cd build

CXX=g++ CC=gcc cmake .. -DCMAKE_INSTALL_PREFIX=../install \
-DProtobuf_LIBRARY_RELEASE=$PROTOBUF_DIR/lib/libprotobuf.so \
-DProtobuf_LITE_LIBRARY_RELEASE=$PROTOBUF_DIR/lib/libprotobuf-lite.so \
-DProtobuf_INCLUDE_DIR=$PROTOBUF_DIR/include \
-DProtobuf_PROTOC_EXECUTABLE=$PROTOBUF_DIR/bin/protoc \
-DProtobuf_PROTOC_LIBRARY_RELEASE=$PROTOBUF_DIR/lib/libprotoc.so \
-DZLIB_LIBRARY_RELEASE=/usr/lib64/libz.so.1 \
-DBUILD_GUI=OFF \
-DCMAKE_PREFIX_PATH=$PWD/../install
make -j16
```

Here in the last step when running `make` where it is linking CMUSEN, I get the following error

```
[100%] Linking CXX executable CMUSEN
libmusen.a(ScriptRunner.cpp.o): In function `std::filesystem::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::filesystem::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::filesystem::__cxx11::path::format)':
ScriptRunner.cpp:(.text._ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC5INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE]+0x64): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
libmusen.a(ExportAsText.cpp.o): In function `CExportAsText::SetFileName(std::filesystem::__cxx11::path const&)':
ExportAsText.cpp:(.text+0xf1): undefined reference to `std::filesystem::__cxx11::path::replace_extension(std::filesystem::__cxx11::path const&)'
libmusen.a(ExportAsText.cpp.o): In function `CExportAsText::PrepareTDData()':
ExportAsText.cpp:(.text+0x2115): undefined reference to `std::filesystem::resize_file(std::filesystem::__cxx11::path const&, unsigned long)'
libmusen.a(ExportAsText.cpp.o): In function `CExportAsText::TryOpenFileW(std::basic_ofstream<char, std::char_traits<char> >&, std::filesystem::__cxx11::path const&, std::_Ios_Openmode)':
ExportAsText.cpp:(.text+0x460a): undefined reference to `std::filesystem::__cxx11::path::parent_path() const'
ExportAsText.cpp:(.text+0x4619): undefined reference to `std::filesystem::create_directories(std::filesystem::__cxx11::path const&)'
ExportAsText.cpp:(.text+0x469c): undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'
ExportAsText.cpp:(.text+0x4735): undefined reference to `std::filesystem::__cxx11::path::parent_path() const'
libmusen.a(ExportAsText.cpp.o): In function `CExportAsText::TryOpenFileR(std::basic_ifstream<char, std::char_traits<char> >&, std::filesystem::__cxx11::path const&, std::_Ios_Openmode)':
ExportAsText.cpp:(.text+0x48ca): undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'
libmusen.a(ExportAsText.cpp.o): In function `CExportAsText::Finalize()':
ExportAsText.cpp:(.text+0x4a4e): undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
libmusen.a(ExportAsText.cpp.o): In function `std::filesystem::__cxx11::path::operator/=(std::filesystem::__cxx11::path const&)':
ExportAsText.cpp:(.text._ZNSt10filesystem7__cxx114pathdVERKS1_[_ZNSt10filesystem7__cxx114pathdVERKS1_]+0x3d): undefined reference to `std::filesystem::__cxx11::path::has_filename() const'
ExportAsText.cpp:(.text._ZNSt10filesystem7__cxx114pathdVERKS1_[_ZNSt10filesystem7__cxx114pathdVERKS1_]+0x98): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
libmusen.a(ExportAsText.cpp.o): In function `std::filesystem::__cxx11::path::is_absolute() const':
ExportAsText.cpp:(.text._ZNKSt10filesystem7__cxx114path11is_absoluteEv[_ZNKSt10filesystem7__cxx114path11is_absoluteEv]+0x14): undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
libmusen.a(ExportAsText.cpp.o): In function `std::filesystem::exists(std::filesystem::__cxx11::path const&)':
ExportAsText.cpp:(.text._ZNSt10filesystem6existsERKNS_7__cxx114pathE[_ZNSt10filesystem6existsERKNS_7__cxx114pathE]+0x14): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
libmusen.a(ExportAsText.cpp.o): In function `MUSENFileFunctions::IsDirWriteProtected(std::filesystem::__cxx11::path const&)':
ExportAsText.cpp:(.text._ZN18MUSENFileFunctions19IsDirWriteProtectedERKNSt10filesystem7__cxx114pathE[_ZN18MUSENFileFunctions19IsDirWriteProtectedERKNSt10filesystem7__cxx114pathE]+0x120): undefined reference to `std::filesystem::create_directories(std::filesystem::__cxx11::path const&)'
ExportAsText.cpp:(.text._ZN18MUSENFileFunctions19IsDirWriteProtectedERKNSt10filesystem7__cxx114pathE[_ZN18MUSENFileFunctions19IsDirWriteProtectedERKNSt10filesystem7__cxx114pathE]+0x15a): undefined reference to `std::filesystem::remove_all(std::filesystem::__cxx11::path const&)'
libmusen.a(ExportAsText.cpp.o): In function `std::filesystem::__cxx11::path::path<char [18], std::filesystem::__cxx11::path>(char const (&) [18], std::filesystem::__cxx11::path::format)':
ExportAsText.cpp:(.text._ZNSt10filesystem7__cxx114pathC2IA18_cS1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC5IA18_cS1_EERKT_NS1_6formatE]+0x5e): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
libmusen.a(ExportAsText.cpp.o):(.data.rel.local.DW.ref._ZTINSt10filesystem7__cxx1116filesystem_errorE[DW.ref._ZTINSt10filesystem7__cxx1116filesystem_errorE]+0x0): undefined reference to `typeinfo for std::filesystem::__cxx11::filesystem_error'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/CMUSEN.dir/build.make:84: CMUSEN] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/CMUSEN.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

In the next comment I'll cover GCC 12 + CUDA 12

**Comment by secondspass** [comment]
Next I tried to build with GCC 12.2.0 + CUDA 12.6.3

Cleaning up and rebuilding Protobuf as before:
```
wget https://github.com/protocolbuffers/protobuf/releases/download/v21.0/protobuf-cpp-3.21.0.tar.gz
tar xzf protobuf-cpp-3.21.0.tar.gz
cd protobuf-3.21.0
CC=gcc CXX=g++ ./configure --prefix=$PWD/install --enable-shared
make clean
make -j16
make install
export PROTOBUF_DIR=$PWD/install
```

Cleaning up previous build and rebuilding MUSEN same as before:
```
git clone https://github.com/msolids/musen.git
cd musen
bash Version/generate_build_version.sh
mkdir build install
cd build

CXX=g++ CC=gcc cmake .. -DCMAKE_INSTALL_PREFIX=../install \
-DProtobuf_LIBRARY_RELEASE=$PROTOBUF_DIR/lib/libprotobuf.so \
-DProtobuf_LITE_LIBRARY_RELEASE=$PROTOBUF_DIR/lib/libprotobuf-lite.so \
-DProtobuf_INCLUDE_DIR=$PROTOBUF_DIR/include \
-DProtobuf_PROTOC_EXECUTABLE=$PROTOBUF_DIR/bin/protoc \
-DProtobuf_PROTOC_LIBRARY_RELEASE=$PROTOBUF_DIR/lib/libprotoc.so \
-DZLIB_LIBRARY_RELEASE=/usr/lib64/libz.so.1 \
-DBUILD_GUI=OFF \
-DCMAKE_PREFIX_PATH=$PWD/../install
make -j16
```

This also fails at the final linking step

```
[100%] Linking CXX executable CMUSEN
libmusen.a(GPUSimulator.cpp.o): In function `CGPUSimulator::CUDAUpdateVerletLists(std::vector<std::vector<unsigned int, std::allocator<unsigned int> >, std::allocator<std::vector<unsigned int, std::allocator<unsigned int> > > > const&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > > const&, CGPU::SCollisionsHolder&, CGPUSimulator::STempStorage&, bool)':
GPUSimulator.cpp:(.text+0x2cb4): undefined reference to `CGPU::UpdateVerletLists(bool, SGPUParticles const&, SGPUWalls const&, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::host_vector<unsigned int, std::allocator<unsigned int> > const&, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::host_vector<unsigned int, std::allocator<unsigned int> > const&, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::host_vector<unsigned int, std::allocator<unsigned int> > const&, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::host_vector<unsigned char, std::allocator<unsigned char> > const&, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_vector<unsigned int, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_allocator<unsigned int> >&, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_vector<unsigned int, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_allocator<unsigned int> >&, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_vector<unsigned int, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_allocator<unsigned int> >&, SGPUCollisions&) const'
GPUSimulator.cpp:(.text+0x2d3c): undefined reference to `CGPU::SortByDst(unsigned int, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_vector<unsigned int, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_allocator<unsigned int> > const&, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_vector<unsigned int, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_allocator<unsigned int> > const&, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_vector<unsigned int, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_allocator<unsigned int> >&, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_vector<unsigned int, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::device_allocator<unsigned int> >&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/CMUSEN.dir/build.make:84: CMUSEN] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/CMUSEN.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by vasylskorych** [comment]
Partially fixed in #47. Also, see CUDA-GCC compatibilty, e.g. here: [https://gist.github.com/ax3l/9489132](https://gist.github.com/ax3l/9489132)
